# Generated by Django 5.0.6 on 2024-08-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_order_city_order_fname_order_lname_order_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
